# Generated by Django 4.1.7 on 2023-03-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Data'),
        ),
    ]
